package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseServActivelist<M extends BaseServActivelist<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 活动标题
	 */
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	/**
	 * 活动标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 活动开始
	 */
	public M setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
		return (M)this;
	}
	
	/**
	 * 活动开始
	 */
	public java.util.Date getStarttime() {
		return get("starttime");
	}

	/**
	 * 结束时间
	 */
	public M setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
		return (M)this;
	}
	
	/**
	 * 结束时间
	 */
	public java.util.Date getEndtime() {
		return get("endtime");
	}

	/**
	 * 活动内容
	 */
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	/**
	 * 活动内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

}
