package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseServActivelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServActivelist extends BaseServActivelist<ServActivelist> {
	public static final ServActivelist dao = new ServActivelist().dao();
}
