package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseServReqfeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServReqfeedback extends BaseServReqfeedback<ServReqfeedback> {
	public static final ServReqfeedback dao = new ServReqfeedback().dao();
}
